### ISSUE TITLE
Canviar les peticions SOAP per peticions REST (API firma simple) cap a Portafib 

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/helium#1551]
En qualque moment es fa una petició SOAP al següent servei de Portafib: https://<entrono>.caib.es/portafib/ws/v1/PortaFIBPassarelaDeFirmaEnServidor per signar en servidor. S'ha de canviar perquè totes les funcionalitats cridin a serveis REST i no hi hagi peticions SOAP cap a Portafib. L'API SOAP està en desús i es vol eliminar.

**Comment by josepg-limit** [comment]
Issue relacionada amb el canvi a l'API simple del Portasignatures #1545

**Comment by josepg-limit** [comment]
En la propera versió d'Helium 3.2.115 migraran les integracions amb WS SOAP del Portasignatures de la firma web i l'enviament de documents al Portasignatures.
