### ISSUE TITLE
Crear regles a Distribucio amb l'opció de "no presencial" amb Distribucio 0.9.49

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/helium#1687]
Quan es publiqui Distribucio 0.9.49 amb les opcions a l'hora de crear i modificar regles s'han de donar d'alta les regles a Distribucio amb l'opció de filtre de rebre només les no presencials per evitar errors de processament. Aprofitar per mostar les opcions a l'usuari a l'hora de crear, consultar i modificar regles.

**Comment by acuevas-dgtic** [comment]
Rel·lacionat amb https://github.com/GovernIB/distribucio/issues/590

**Comment by josepg-limit** [comment]
Fet a la issue #1700 de la versió 3.2.116.2.
